# Generated by Django 5.0.7 on 2024-07-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="available_seats",
            new_name="occupied_seats",
        ),
        migrations.AddField(
            model_name="course",
            name="total_seats",
            field=models.IntegerField(default=0),
        ),
    ]
